### ISSUE TITLE
dtube.video is constantly making requests against localhost at port 5001

### ISSUE THREAD

**Issue by muksihs** [dtube/about#1]
dtube.video is constantly making requests against localhost at port 5001

![image](https://user-images.githubusercontent.com/32560971/31262441-eece3312-aa28-11e7-8230-914646ea20e1.png)

**Comment by mktcode** [comment]
Thank you! Heimindanger is informed!
But I will close your two issues because this repo is just for the new about page and not dtube itself. There will be a repo for dtube in the future.
