### ISSUE TITLE
The NSFW videos setting is reset on page load.

### ISSUE THREAD

**Issue by muksihs** [dtube/about#2]
The NSFW video setting is reset on page load. Shouldn't this be a per browser setting? I find the current behavior counter intuitive, if I set it to enable NSFW content, it would be nice for it to stay that way to keep me from getting confused as to why my own videos keeping getting hidden from me.

![image](https://user-images.githubusercontent.com/32560971/31262499-56f7de66-aa29-11e7-92d8-cf3ebdbffc61.png)

**Comment by mktcode** [comment]
See #1
